enum ModalKeyEnum {
	AppliedModal = 'AppliedModal',
	ApplyCancelModal = 'ApplyCancelModal',
	ApplyModal = 'ApplyModal',
	ApproveCancelModal = 'ApproveCancelModal',
	EditCategoryModal = 'EditCategoryModal',
	EditStudyModal = 'EditStudyModal',
	EditProfileImageModal = 'EditProfileImageModal',
	HostStudyMoreModal = 'HostStudyMoreModal',
	LoginModal = 'LoginModal',
	MyCategoryModal = 'MyCategoryModal',
	NotificationModal = 'NotificationModal',
	ReportModal = 'ReportModal',
	StudyApproveModal = 'StudyApproveModal',
	StudyCloseModal = 'StudyCloseModal',
	StudyDeleteModal = 'StudyDeleteModal',
	StudyFilterModal = 'StudyFilterModal',
	StudyPostModal = 'StudyPostModal',
	StudySearchModal = 'StudySearchModal',
	StudySortModal = 'StudySortModal',
	UserStudyMoreModal = 'UserStudyMoreModal',
	UserProfileModal = 'UserProfileModal',
	WithdrawModal = 'WithdrawModal',
}

export default ModalKeyEnum;
